# Generated by Django 2.2.8 on 2019-12-19 22:14

from django.db import migrations, models
import django.db.models.deletion
import post_office.fields
import post_office.validators


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('post_office', '0008_attachment_headers'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', help_text='The email recipients.', verbose_name='Send to group'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(help_text='The template name', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='email',
            name='bcc',
            field=post_office.fields.CommaSeparatedEmailField(blank=True, help_text='Separate multiple addresses with a comma.', verbose_name='Bcc'),
        ),
        migrations.AlterField(
            model_name='email',
            name='cc',
            field=post_office.fields.CommaSeparatedEmailField(blank=True, help_text='Separate multiple addresses with a comma.', verbose_name='Cc'),
        ),
        migrations.AlterField(
            model_name='email',
            name='from_email',
            field=models.CharField(help_text='Must have permission to send through the default server!', max_length=254, validators=[post_office.validators.validate_email_with_name], verbose_name='Email From'),
        ),
        migrations.AlterField(
            model_name='email',
            name='html_message',
            field=models.TextField(blank=True, verbose_name='HTML Content'),
        ),
        migrations.AlterField(
            model_name='email',
            name='message',
            field=models.TextField(blank=True, verbose_name='Text Content'),
        ),
        migrations.AlterField(
            model_name='email',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Scheduled sending time'),
        ),
        migrations.AlterField(
            model_name='email',
            name='to',
            field=post_office.fields.CommaSeparatedEmailField(blank=True, help_text='Separate multiple addresses with a comma.', verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='content',
            field=models.TextField(blank=True, validators=[post_office.validators.validate_template_syntax], verbose_name='Text Content'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_content',
            field=models.TextField(blank=True, validators=[post_office.validators.validate_template_syntax], verbose_name='HTML Content'),
        ),
    ]
