# Generated by Django 2.2.9 on 2020-01-09 03:39

from django.db import migrations, models
import post_office.validators


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0010_auto_20200106_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='content',
            field=models.TextField(blank=True, default='\n\nClick the following link to unsubscribe from future emails: \nhttps://{{ unsubscribe }}', help_text='Plain text message for users who have HTML email disabled.', validators=[post_office.validators.validate_template_syntax], verbose_name='Text Content'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_content',
            field=models.TextField(blank=True, default='<br /><br /><p style="text-align:center;font-size:small;"">Click <a href=https://{{ unsubscribe }}>here</a> to unsubscribe from future emails.</p>', help_text='Email HTML body. Context variables available for personalisation, ex: {{ first_name }} {{ last_name }} returns Joe Smith', validators=[post_office.validators.validate_template_syntax], verbose_name='HTML Content'),
        ),
    ]
