# Generated by Django 2.2.10 on 2020-02-19 07:37

from django.db import migrations, models
import django.db.models.deletion
import post_office.fields
import post_office.validators


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0012_auto_20200116_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='bcc',
            field=post_office.fields.CommaSeparatedEmailField(blank=True, help_text='Optional, separate multiple addresses with a comma.', verbose_name='Email Bcc'),
        ),
        migrations.AlterField(
            model_name='email',
            name='cc',
            field=post_office.fields.CommaSeparatedEmailField(blank=True, help_text='Optional, separate multiple addresses with a comma.', verbose_name='Email Cc'),
        ),
        migrations.AlterField(
            model_name='email',
            name='from_email',
            field=models.CharField(help_text='Must have permission to send through the default server!', max_length=254, validators=[post_office.validators.validate_email_with_name], verbose_name='Email From'),
        ),
        migrations.AlterField(
            model_name='email',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Send email to all members of a group.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group', verbose_name='Send to group'),
        ),
        migrations.AlterField(
            model_name='email',
            name='html_message',
            field=models.TextField(blank=True, help_text='Leave this blank if sending content by a template!', verbose_name='HTML Content'),
        ),
        migrations.AlterField(
            model_name='email',
            name='message',
            field=models.TextField(blank=True, help_text='Leave this blank if sending content by a template!', verbose_name='Text Content'),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(blank=True, help_text='Leave this blank if sending content by a template!', max_length=989, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='email',
            name='template',
            field=models.ForeignKey(blank=True, help_text='If selected, will replace subject, plain-text content, and html content with content from the chosen template.', null=True, on_delete=django.db.models.deletion.CASCADE, to='post_office.EmailTemplate', verbose_name='Email template'),
        ),
        migrations.AlterField(
            model_name='email',
            name='to',
            field=post_office.fields.CommaSeparatedEmailField(blank=True, help_text='Optional (if no group of recipients selected), separate addresses with a comma.', verbose_name='Email To'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='content',
            field=models.TextField(blank=True, help_text='Plain text message for users who have HTML email disabled.', validators=[post_office.validators.validate_template_syntax], verbose_name='Text Content'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='description',
            field=models.CharField(blank=True, help_text='Description of this template.', max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_content',
            field=models.TextField(blank=True, help_text='Email HTML body. Context variables available for personalisation, ex: {{ first_name }} {{ last_name }} returns Joe Smith', validators=[post_office.validators.validate_template_syntax], verbose_name='HTML Content'),
        ),
    ]
